# Do a full check of everything.
[tasks.complete-check]
dependencies = [
  "format",
  "spellcheck",
  "check",
  "clippy",
  "test",
  "code-coverage",
  "docs",
  "build",
  "audit-flow",
  "outdated-flow",
]

# Run cargo-tarpaulin and output the test coverage.
[tasks.code-coverage]
workspace = false
command = "cargo"
args = [
  "tarpaulin",
  "--exclude-files=target/*",
  "--out=html",
  "--output-dir=coverage",
  "--skip-clean",
  "--target-dir=target/tarpaulin",
]

# Do a source code spellcheck.
[tasks.spellcheck]
clear = true
command = "typos"
